a16z/jolt

- EngineeringOverview.md
- README.md
- src/benches/bench.rs
- src/e2e_test.rs
- src/lasso/densified.rs
- src/lasso/surge.rs
`SparseLookupMatrix` doesn't do much anymore, fold it into `DensifiedRepresentation::from_lookup_indices` (previously `DensifiedRepresentation::from`)
> refactor: Delete `SparseLookupMatrix`

- src/subtables/and.rs
- src/subtables/or.rs
- src/subtables/xor.rs
For bitwise AND, OR, and XOR, the subtable entries are $\log M / 2$ bits  –– the subtable entries are half the size of the subtable indices (indices are two operands)
> Fix combine_lookups increment for bitwise ops

- src/lasso/memory_checking.rs
- src/lasso/surge.rs
- src/subprotocols/sumcheck.rs
- src/subtables/mod.rs
Closes #33. It builds upon #41, additionally toggling the parallelism based on the multicore feature (per @sragss's feedback) and fixing a bug in the sumcheck protocol that prevents compilation when not using the multicore feature.
> feat(parallelize): add parallelism to to_grand_products

- src/jolt/instruction/jalr.rs
- src/jolt/instruction/mod.rs
- src/jolt/subtable/mod.rs
- src/jolt/subtable/zero_lsb.rs
With the zero_lsb subtable. Given x, y as input, the table entry is the lower 64 bits of z = x+y+4 with the LSB of z set to 0. (In the full system, the R1CS will handle the calculation and send just the 65-bit z to the lookup.)
> JALR Instruction 

- src/jolt/instruction/add.rs
- src/jolt/instruction/and.rs
- src/jolt/instruction/beq.rs
- src/jolt/instruction/bge.rs
- src/jolt/instruction/bgeu.rs
- src/jolt/instruction/bne.rs
- src/jolt/instruction/jal.rs
- src/jolt/instruction/jalr.rs
- src/jolt/instruction/mod.rs
- src/jolt/instruction/or.rs
- src/jolt/instruction/sll.rs
- src/jolt/instruction/slt.rs
- src/jolt/instruction/sltu.rs
- src/jolt/instruction/sub.rs
- src/jolt/instruction/test.rs
- src/jolt/instruction/xor.rs
- src/jolt/vm/mod.rs
- src/jolt/vm/test_vm.rs
- src/lasso/surge_2.rs
Requires threading C through the `subtables` method
> [JOLT-45] Make SLLInstruction generic-ish over C

- jolt-core/build.rs
- jolt-core/src/r1cs/circuits/compile_jolt.sh
- jolt-core/src/r1cs/scripts/compile_jolt.sh
- jolt-core/src/r1cs/snark.rs
- Stores the compiled artifacts to `./target/<build type>/jolt-core-<post-fix>/out/circom/...`
- Stores this path to `CIRCUIT_DIR`
- `snark.rs` reads `CIRCUIT_DIR`
> Build jolt.circom via Cargo

- jolt-core/src/r1cs/circuits/jolt.circom
Changed the circom file to take inputs with the new format consistent with the vectors produced by the rest of Jolt. Compiler variables to be set are in a function at the top. Currently hardcoded to test that circom compiles, but I can change it in build.rs once we're okay with the design. 
It's currently 35 r1cs constraints btw. Haven't tried to optimize yet but it's still really good for now.
I've tried to add more documentation to the variables and constraints but it'll definitely need more. When you guys have a look, lemme know what's missing or confusing.
There are some minor TODOs: 
1. If regs and RAM are in the same address space, we need to reflect how they're encoded here.
2. Loads require sign-extension which I haven't added yet.
> updated to new circom format

- Cargo.toml
- examples/fibonacci/Cargo.toml
- examples/fibonacci/build.rs
- examples/fibonacci/linker.ld
- examples/fibonacci/src/entry.s
- examples/fibonacci/src/main.rs
- examples/hash/Cargo.toml
- examples/hash/build.rs
- examples/hash/linker.ld
- examples/hash/src/entry.s
- examples/hash/src/main.rs
Adds example programs for fibonacci and keccak hashing. To build either, run `cargo build --release -p hash` or `cargo build --release -p fibonacci`. The binary elf files should then be in `target/riscv32i-unknown-none-elf/release`.
> feat: add example programs

- tracer/Cargo.toml
- tracer/src/decode.rs
- tracer/src/emulator/cpu.rs
- tracer/src/lib.rs
- tracer/src/main.rs
Adds a `decode` function which decodes an elf file and returns `Vec<common::Instruction>`. One important thing to note is that even though I think the instructions should be in order with no gaps, there is a chance the compiler doesn't do this (there is no requirement that the different text sections be laid out in order without gaps, but in my testing they seem to). I'd just go by the `address` of each instruction rather than the location in the vector. 
I'm happy to make some changes here to make understanding the different sections (rather than concatenating everything) easier. Alternatively we can check for consistency and panic if anything is not laid out nicely, and cross that bridge if it ever comes up.
> feat: decode elf files

- README.md
- jolt-core/Cargo.toml
- jolt-core/src/benches/bench.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/lasso/surge.rs
- jolt-core/src/main.rs
Adds `plot` CLI command to plot runtime of proving benchmarks (prove_bytecode, prove_memory, prove_instruction_lookups) against one of three independent variables: bytecode size, memory size, or # cycles (fixing the other two). Outputs to the terminal using textplots, and optionally saves an SVG file using plotters too.
> Add plot CLI command

- common/src/field_conversion.rs
- common/src/lib.rs
- jolt-core/src/jolt/instruction/add.rs
- jolt-core/src/jolt/instruction/and.rs
- jolt-core/src/jolt/instruction/beq.rs
- jolt-core/src/jolt/instruction/bge.rs
- jolt-core/src/jolt/instruction/bgeu.rs
- jolt-core/src/jolt/instruction/blt.rs
- jolt-core/src/jolt/instruction/bltu.rs
- jolt-core/src/jolt/instruction/bne.rs
- jolt-core/src/jolt/instruction/jal.rs
- jolt-core/src/jolt/instruction/jalr.rs
- jolt-core/src/jolt/instruction/mod.rs
- jolt-core/src/jolt/instruction/or.rs
- jolt-core/src/jolt/instruction/sll.rs
- jolt-core/src/jolt/instruction/slt.rs
- jolt-core/src/jolt/instruction/sltu.rs
- jolt-core/src/jolt/instruction/sra.rs
- jolt-core/src/jolt/instruction/srl.rs
- jolt-core/src/jolt/instruction/sub.rs
- jolt-core/src/jolt/instruction/xor.rs
- jolt-core/src/jolt/trace/rv.rs
- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/jolt/vm/rv32i_vm.rs
- jolt-core/src/r1cs/circuits/jolt.circom
- jolt-core/src/r1cs/snark.rs
- jolt-core/src/utils/instruction_utils.rs
- tracer/src/emulator/cpu.rs
Adds the `prove_r1cs` function in the Jolt trait. Able to generate proofs using the
> Generating Spartan proofs in VM module using R1CS module 

- jolt-core/src/msm/mod.rs
Backporting https://github.com/arkworks-rs/algebra/pull/703 for 8-12% improvement when running with parallel execution.
> Backport small MSM improvement

- jolt-core/Cargo.toml
- jolt-core/benches/materialize.rs
- jolt-core/src/jolt/subtable/eq.rs
- jolt-core/src/jolt/subtable/eq_abs.rs
Probably in the grand scheme of things these savings are negligible, but here they are:
before:
```
DenseMLPoly Evaluation/Materialize EQ subtable
time:   [211.17 µs 213.41 µs 216.47 µs]
DenseMLPoly Evaluation/Materialize EQAbs subtable
time:   [217.81 µs 223.26 µs 229.77 µs]
```
after:
```
DenseMLPoly Evaluation/Materialize EQ subtable
time:   [91.029 µs 92.311 µs 93.933 µs]
change: [-57.152% -56.489% -55.796%] (p = 0.00 < 0.05)
DenseMLPoly Evaluation/Materialize EQAbs subtable
time:   [90.391 µs 91.322 µs 92.320 µs]
change: [-58.382% -57.365% -56.325%] (p = 0.00 < 0.05)
```
> Optimized materialization of `EQ` tables

- jolt-core/src/r1cs/snark.rs
This synthesizes only variables when calling `JoltCircuit.synthesize`, and not the constraints. Synthesizing constraints in only needed when generating the shape and that's handled in `JoltSkeleton.synthesize`. 
For the 32k hash trace, the total time spent in synthesize halves (670 ms -> 310 ms) on my system. It's overall not a major cost now anyway but I think it'll be significant as the trace lengths improve. 
(We didn't need to modify any of circom scotia or Spartan for this.)
> synthesize only variables during proof (and not shape)

- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/lasso/surge.rs
- jolt-core/src/msm/mod.rs
- jolt-core/src/poly/dense_mlpoly.rs
Slowly preparing for [generalizing](https://github.com/a16z/Lasso/issues/8) the [PCS](https://github.com/a16z/Lasso/pull/66), which would require switching to `MultilinearExtension` from `ark-poly` and deprecating the custom `DensePolynomial` used now.
This PR should be useful regardless of whether the above happens or not:
1. Removes `merge_dual` in favor of calling `merge` on the concatenated slices
2. Removes unused `extend`
3. msm-based functionality (`flag_msm` & `sm_msm`) are not methods on `DensePolynomial` but rather stand-alone functions. Moves them to the `msm` module.
> Cleanup dense poly

- jolt-core/src/jolt/subtable/sra_sign.rs
- jolt-core/src/jolt/vm/instruction_lookups.rs
`SraSignSubtable::materialize` was 40x slower than the next closest bottlnecking materialize step. Small win overall.
> optimize: SraSignSubtable materialize

- jolt-core/src/jolt/vm/timestamp_range_check.rs
These take 95%+ of the function. Speeds it up by roughly `num_threads / 2`. Slowness is due to the fact that each `F::from` does a field multiplication. 
We can theoretically make this faster with the table method: Precompute a table in the range say [0..1 << 10] then construct the `DensePolynomial<F>` from the table. This would skip the field multiplication in most cases. For a 512k trace this takes a few bips of time so likely not worth the complexity.
> optimize: RangeCheckPolynomials::construct

- Cargo.toml
4x faster hot builds, with no perceptible change in runtime speed
> build-fast profile

- common/Cargo.toml
- common/src/field_conversion.rs
- jolt-core/Cargo.toml
- jolt-core/src/r1cs/snark.rs
- jolt-core/src/utils/mod.rs
- jolt-core/src/utils/thread.rs
- Fixes `reassemble_by_segments` algorithm to be 90% faster
- Introduces `unsafe` conversions between Spartan <==> Arkworks representations of 256-bit fields by unsafely casting directly between the two. Otherwise conversions incurred 1-2 field multiplications when converting in and out of montgomery form.
- Reduces cost of Witness computation by 90%. Reduces pre-snark input conversion cost 95%. 
- Points to a fork of `circom-witness-rs` which has an `evaluate_fr` function so we can evaluate the witness using the Arkworks scalar field type rather than: `ark_bn256::Fr -> halo2_curves::bn256::Fr -> Ruint::U256 -> ark_bn256::Fr -> RuintU256 -> halo2_curves::bn256::Fr`. Now we do`ark_bn256::Fr -> halo2_curves::bn256::Fr -> ark_bn256::Fr -> halo2_curves::bn256::Fr` but thanks to the bullet …
> feat: Speed up JoltCircuit::synthesize

- jolt-core/src/jolt/instruction/add.rs
- jolt-core/src/jolt/instruction/and.rs
- jolt-core/src/jolt/instruction/beq.rs
- jolt-core/src/jolt/instruction/bge.rs
- jolt-core/src/jolt/instruction/bgeu.rs
- jolt-core/src/jolt/instruction/blt.rs
- jolt-core/src/jolt/instruction/bltu.rs
- jolt-core/src/jolt/instruction/bne.rs
- jolt-core/src/jolt/instruction/mod.rs
- jolt-core/src/jolt/instruction/or.rs
- jolt-core/src/jolt/instruction/sll.rs
- jolt-core/src/jolt/instruction/slt.rs
- jolt-core/src/jolt/instruction/sltu.rs
- jolt-core/src/jolt/instruction/sra.rs
- jolt-core/src/jolt/instruction/srl.rs
- jolt-core/src/jolt/instruction/sub.rs
- jolt-core/src/jolt/instruction/test.rs
- jolt-core/src/jolt/instruction/xor.rs
- jolt-core/src/jolt/trace/rv.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/jolt/vm/rv32i_vm.rs
Saves 5-7% e2e by computing the lookup outputs in `u64`.
> optimize: efficiently compute lookup outputs

- common/Cargo.toml
- common/src/field_conversion.rs
@sragss reached me about my [implementation](https://github.com/zkmove/halo2-verifier.move/blob/main/crates/vk-gen-examples/src/to_ark.rs) of the conversion between ark and halo2curves.
He suggests I provide the impl to the repo, so here we are.
> implement the bn256 curve conversion between ark and halo2curves

- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/poly/dense_mlpoly.rs
- jolt-core/src/poly/hyrax.rs
- jolt-core/src/r1cs/snark.rs
Smooths out the parallelism when committing to a batch of polynomials. Significant improvement for commit_segments
> Hyrax batch commit

- Cargo.toml
- src/lib.rs
- src/main.rs
To install run: `cargo install --git https://github.com/a16z/Lasso --branch jolt --force` (will only work after merge)
To install toolchain run: `jolt install-toolchain`
To create new project run `jolt new <NAME>` and a new directory will be created with the name <NAME> and a simple fibonacci example.
Note: we will need to update the branch in the toml file once we change the branch from jolt to master.
For some reason I have to import jolt_sdk directly rather than jolt or the no_std in the guest compilation is not respected. I'd like to fix this but am unsure how. If anyone has any ideas let me know.
> feat: add jolt tool

- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/r1cs/constraints.rs
- jolt-core/src/r1cs/r1cs_shape.rs
- jolt-core/src/r1cs/snark.rs
- jolt-core/src/r1cs/spartan.rs
Adds a constraint per step that checks that the output PC of step i is the input PC to step i+1. This is only enforced for the true (non padded) steps of the trace, which is passed as a new variable. 
This requires modifying the r1cs matrix-vector multiplication and the MLE evaluations for both the prover and verifier. 
(There are optimizations that improve overall performance and also avoid this, but require changing the trace.)
> IO consistency constraints

- src/main.rs
There was N missing in `GITIGORE`.
> chore: Fix spelling of GITIGNORE

- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/r1cs/snark.rs
Solves #295
I had to refactor `R1CSInputs` a bit, to accept references
Doing benchmarks on my machine using `cargo run --profile build-fast -p jolt-core trace --name sha3 --format chrome` `get_poly_r1cs` gets a ~5x improvement (`138ms` to `38ms`)
> Refactoring get_polys_r1cs to use references instead of cloning

- Cargo.toml
- examples/alloc/Cargo.toml
- examples/collatz/Cargo.toml
- examples/fibonacci/Cargo.toml
- examples/multi-function/Cargo.toml
- examples/sha2-chain/Cargo.toml
- examples/sha2-ex/Cargo.toml
- examples/sha3-chain/Cargo.toml
- examples/sha3-ex/Cargo.toml
- examples/stdlib/Cargo.toml
- examples/stdlib/guest/Cargo.toml
- examples/stdlib/guest/src/lib.rs
- examples/stdlib/src/main.rs
- jolt-core/src/host/mod.rs
- jolt-sdk/Cargo.toml
- jolt-sdk/macros/Cargo.toml
- jolt-sdk/macros/src/lib.rs
- jolt-sdk/src/alloc.rs
- jolt-sdk/src/host_utils.rs
- jolt-sdk/src/lib.rs
- src/main.rs
- tracer/src/emulator/cpu.rs
Adds support for the standard library in guests. This is done by adding the `guest-std` flag when importing jolt in the guest. Also note that the flag supplied to the sdk when called from the host has changed from `std` to `host` to avoid confusion (although existing programs will need to be updated).
To use this, you need to have a custom rust toolchain by running `jolt install-toolchain` with this version of the jolt tool.
I've also noticed a few bugs that crop up when tracing and proving some programs generated with the standard library which we should get to the bottom of.
> feat: standard library support

- common/src/constants.rs
- examples/sha2-ex/src/main.rs
- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/jolt/vm/timestamp_range_check.rs
- jolt-core/src/lasso/surge.rs
- jolt-core/src/poly/commitment/commitment_scheme.rs
- jolt-core/src/poly/commitment/hyrax.rs
- jolt-core/src/r1cs/snark.rs
- jolt-core/src/r1cs/spartan.rs
Includes a `batch_size` param in calls to `CommitmentScheme::{batch_commit, batch_prove}` and includes the `batch_size` param in the `CommitmentScheme::BatchedProof` struct if needed.
Two unfortunate things:
- Leaky abstraction: Hyrax is the only commitment scheme we know about that needs the `batch_size` param to be used as the Hyrax sizing ratio. Theoretically this could be refactored to be an associated type on `CommitmentScheme` called `BatchCommitConfig` which could store other info, we just aren't aware of another commitment scheme that needs it.
- Bad parameter naming: `batch_size` isn't quite the correct parameter name. Currently we call `CommitmentScheme::{batch_commit, batch_prove}` for a range of *real* batch sizes {163, 40}. Across all of these `NUM_R1CS_POLYS=64` is close …
> Refactor Hyrax Batching

- jolt-core/src/r1cs/spartan.rs
Saves ~1.75% e2e time on 4M trace length on the default linux allocator.
> SegmentedPaddedWitness: Drop EqPoly Bkg

- book/src/background.md
- book/src/dev/install.md
- book/src/how_it_works.md
- A link of the book is invalid: https://jolt.a16zcrypto.com/how_it_works.html (Jolt link)
- The Background note is missing the batched polynomial opening notes in the summary https://jolt.a16zcrypto.com/background.html
- Added more instructions on how to install the book locally https://jolt.a16zcrypto.com/dev/install.html
> Update links and add more instructions to install the book locally

- examples/sha2-chain/Cargo.toml
- examples/sha2-chain/guest/src/lib.rs
- examples/sha2-chain/src/main.rs
This PR fixes the chaining of hashes in the `sha2-chain` example.
> Fix: Chaining Hashes in `sha2-chain` Example

- jolt-core/src/jolt/vm/read_write_memory.rs
Resolves two of the three todos reducing the memory use of the verifier when calculating the evaluations of the initial memory polynomials. Resolves #350
> Efficent opening proofs in verifier

- jolt-core/Cargo.toml
The only place where `iai-callgrind` is used is jolt-core/bench/iai.rs, which is outside of `jolt-core/src` and should be moved into `dev-depencency`
And, similar to criterion, it will cause jolt to fail to compile into wasm
https://github.com/a16z/jolt/issues/345
> move iai-callgrind to dev-depencency

- jolt-core/src/jolt/instruction/mod.rs
- jolt-core/src/jolt/instruction/movsign.rs
We now support the MOVSIGN instruction as part of the RISCV M extensions
> feat(jolt-core): Adding MOVSIGN instruction

- .github/workflows/rust.yml
- src/main.rs
Make updating the toolchain a matter of adjusting the settings in `rust-toolchain.toml` (vs updating them in multiple places):
- CI: install toolchain in actions from rust-toolchain.toml
- Reuse rust-toolchain.toml for guests (as it's exactly the same)
> Deduplicate Rust toolchain settings

- jolt-core/Cargo.toml
- jolt-core/src/lib.rs
When I comiple the jolt-core to wasm:
```shell
Compiling jolt-core v0.1.0 (https://github.com/a16z/jolt#6083da83)
error[E0432]: unresolved import `tokio::runtime::Runtime`
--> /Users/flyq/.cargo/git/checkouts/jolt-6b856340b98daf0c/6083da8/jolt-core/src/host/toolchain.rs:12:5
|
12 | use tokio::runtime::Runtime;
|     ^^^^^^^^^^^^^^^^^^^^^^^ no `Runtime` in `runtime`
error[E0433]: failed to resolve: could not find `time` in `tokio`
--> /Users/flyq/.cargo/git/checkouts/jolt-6b856340b98daf0c/6083da8/jolt-core/src/host/toolchain.rs:49:24
|
49  |                 tokio::time::sleep(std::time::Duration::from_millis(timeout)).await;
|                        ^^^^ could not find `time` in `tokio`
|
note: found an item that was configured out
--> …
```
> add host feature to jolt-core

- jolt-core/Cargo.toml
- jolt-core/src/msm/mod.rs
- jolt-core/src/poly/commitment/hyperkzg.rs
- jolt-core/src/poly/commitment/kzg.rs
- jolt-core/src/poly/commitment/zeromorph.rs
- jolt-core/src/poly/unipoly.rs
- jolt-core/src/utils/mod.rs
Also adds some tracing spans for Zeromorph/HyperKZG and removes the last vestiges of the `multicore` feature
> Optimize Zeromorph and HyperKZG batch opening proofs

- jolt-core/src/poly/commitment/commitment_scheme.rs
- jolt-core/src/subprotocols/grand_product_quarks.rs
- jolt-core/src/subprotocols/mod.rs
Implements a version of the grand product argument from the Quarks [paper](https://eprint.iacr.org/2020/1275), this version is the simpler version from the section 5 of the paper which directly trades off increased prover time for reducing proof size from log^2(n) to just log(n). Depending on the performance we may or may not followup with a hybrid approach from section 6.
Note - This just adds the sub protocol, it doesn't wire a default proof to use quarks.
> Implementation of section 5 of the Quarks Paper

- jolt-core/src/r1cs/builder.rs
- jolt-core/src/r1cs/jolt_constraints.rs
- jolt-core/src/r1cs/ops.rs
- jolt-core/src/r1cs/test.rs
Aux computation now deduplicates evaluation of Linear Combinations shared across the auxiliary variables. 28% of Linear Combinations are currently reused in `jolt_constraints.rs` and were previously computed from scratch. 35% speed up over existing on 2^22 trace length 50bps reduction e2e.
In the process removes `AuxComputation.{flat_vars, inputs_to_flat}`.
Separately speeds up + cleans up `CombinedUniformBuilder::compute_spartan_Az_Bz_Cz` by moving the batch LC evaluation logic onto LC.
> feat: Improve Aux computation

- jolt-core/src/benches/bench.rs
- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/jolt/vm/timestamp_range_check.rs
- jolt-core/src/lasso/memory_checking.rs
- jolt-core/src/lasso/surge.rs
- jolt-core/src/subprotocols/grand_product.rs
- jolt-core/src/subprotocols/grand_product_quarks.rs
Updates the batched product type to support a quark proof or a thaler 13 proof type and changes the invocations of the product. In addition makes edits to the quark product type to support section six of the quarks paper which does a hybrid of Thaler '13 grand products by applying quarks at the 4th layer of the GKR for grand products.
Resolves #250
> Updates to BatchedProduct to enable Quark section 6

- jolt-core/src/jolt/vm/rv32i_vm.rs
`fib_e2e` is parameterized with `<F: JoltField, PCS: CommitmentScheme<Field = F>>`, but is currently using a concrete field and commitment scheme instead of them:
```rust
let (proof, commitments) =
<RV32IJoltVM as Jolt<Fr, HyraxScheme<G1Projective>, C, M>>::prove(
io_device,
trace,
circuit_flags,
preprocessing.clone(),
);
```
Given there are multiple tests calling `fib_e2e` with different implementations of JoltField and CommitmentScheme, this is probably not intended.
> fib_e2e: Actually use the type parameters 🙃

- .github/workflows/rust.yml
- .jolt.rust.toolchain-tag
- jolt-core/src/host/toolchain.rs
Let tests rely on toolchain already being present.
Fix #376
> Install Jolt RISC-V toolchain before running tests

- jolt-core/Cargo.toml
This fixes errors that have started popping up in clippy and test CI runs today:
```
Checking jolt-core v0.1.0 (/home/runner/work/jolt/jolt/jolt-core)
error[E0599]: no function or associated item named `new` found for struct `tokio::runtime::Runtime` in the current scope
Error:    --> jolt-core/src/host/toolchain.rs:24:27
|
24  |         let rt = Runtime::new().unwrap();
|                           ^^^ function or associated item not found in `Runtime`
|
note: if you're trying to build a new `tokio::runtime::Runtime`, consider using `tokio::runtime::Runtime::from_parts` which returns `tokio::runtime::Runtime`
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:138:5
|
138 | /     pub(super) fn from_parts(
139 | |         scheduler: …
```
> Fix tokio — this fixes latest compile errors in CI

- jolt-core/Cargo.toml
- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/jolt/vm/timestamp_range_check.rs
- jolt-core/src/lasso/memory_checking.rs
- jolt-core/src/lasso/surge.rs
- jolt-core/src/poly/commitment/binius.rs
- jolt-core/src/poly/commitment/hyperkzg.rs
- jolt-core/src/poly/commitment/hyrax.rs
- jolt-core/src/poly/commitment/mock.rs
- jolt-core/src/poly/commitment/pedersen.rs
- jolt-core/src/poly/commitment/zeromorph.rs
- jolt-core/src/poly/unipoly.rs
- jolt-core/src/r1cs/inputs.rs
- jolt-core/src/r1cs/key.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/grand_product.rs
- jolt-core/src/subprotocols/grand_product_quarks.rs
- jolt-core/src/subprotocols/sumcheck.rs
- jolt-core/src/utils/transcript.rs
Change list:
1. Replaces the Merlin transcript which uses keccack1600 permutations with a transcript which we define for jolt and which uses keccack256. This transcript squeezes all inputs into 32bytes with an action counter. It doesn't abstract over the hasher object to support snark friendly recursion hashes, but this would be only a small change.
2. Removes Merlin from our dependency graph
3. Because we removed Merlin we bump the sha3 version to be modern as opposed to the 5 year old current import, and make small interface changes in key.rs and perdersen.rs
4. Most labels are removed in favor of the increasing index which is hashed into each step.
There is no performance change.
> Adds an onchain compatible transcript and removes Merlin

- Cargo.toml
- common/Cargo.toml
- common/src/attributes.rs
- common/src/lib.rs
- jolt-core/Cargo.toml
- jolt-core/src/host/mod.rs
- jolt-core/src/host/toolchain.rs
- jolt-core/src/utils/profiling.rs
- jolt-sdk/macros/Cargo.toml
- jolt-sdk/macros/src/lib.rs
- jolt-sdk/src/host_utils.rs
- src/build_wasm.rs
- src/main.rs
This pull request introduces WebAssembly (WASM) compatibility for the verification process of Jolt. The main changes include:
- Extension of `jolt new` command with `--wasm` flag:
- The `jolt new <project-name> --wasm` command modifies both the `root/Cargo.toml` and `guest/Cargo.toml` files to include the necessary dependencies for WASM. It also marks the project as a `cdylib` crate type, which is required for WASM compilation.
- Addition of `jolt build-wasm` command
- The `build-wasm` command extracts all functions declared with `jolt::provable`. It then performs preprocessing steps to build and decode the program, storing the resulting data in binary form. An example `index.html` file is created to demonstrate how to use the functions generated by the macro extension. Finally, optimized …
> feat: add WASM compatibility for verification functions

- jolt-core/src/jolt/instruction/mod.rs
- jolt-core/src/jolt/vm/rv32i_vm.rs
At some point the old strategy stopped building for me.
Details from the Rust docs on discriminants: https://doc.rust-lang.org/reference/items/enumerations.html#pointer-casting
> Fix Enum Discriminant

- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/poly/unipoly.rs
- jolt-core/src/subprotocols/sumcheck.rs
We were computing compressed polys but not using them to reduce the committed transcript length despite that appearing to be their purpose.
> Adds compressed polys to transcript instead normal ones

- jolt-core/src/jolt/vm/rv32i_vm.rs
- jolt-sdk/macros/src/lib.rs
- added serialize_to_bytes and deserialize_from_bytes methods to RV32IHyraxProof.
- modified imports to include RV32IHyraxProof in wasm.
- updated deserialization logic in verify_wasm_fn_name to use RV32IHyraxProof::deserialize_from_bytes.
> fix: add deserialize function and change types to RV32IHyraxProof in wasm-related code

- src/build_wasm.rs
Changes:
- Simplified the attribute checking logic in `is_provable`
- Now correctly identifies attributes with the structure `jolt::provable`
While the previous implementation built wasm correctly, the index.html demo was broken. The demo described in the docs will now work as expected.
> fix: refactor check for provable functions in wasm build process

- jolt-core/src/poly/commitment/hyperkzg.rs
- jolt-core/src/poly/commitment/kzg.rs
~20% speedup of KZG and HyperKZG verifiers due to multi-pairing vs 2 individual pairing operations.
> KZG, HyperKZG: speedup pairing checks

- jolt-sdk/macros/src/lib.rs
This adds `Send` and `Sync` to the `Fn`s in the result of generated `build_<guest>` functions, so setup can be more easily shared in `#[test]` and other multithreaded code.
> Make prove and verify closures Sync+Send

- jolt-core/src/jolt/instruction/bge.rs
- jolt-core/src/jolt/instruction/bgeu.rs
- jolt-core/src/jolt/instruction/slt.rs
- jolt-core/src/jolt/instruction/sltu.rs
For the SLT, SLTU, BGE, and BGEU instructions, we do not need the equality lookup on the least significant chunks. This is because the formulas for those instructions (such as SLTU) look like:
SLTU(x, y) = LTU(x_0, y_0) + LTU(x_1, y_1) * EQ(x_0, y_0) + ... + LTU(x_{C-1}, y_{C-1}) * EQ(x_0, y_0) * ... * EQ(x_{C-2}, y_{C-2})
and so the last equality EQ(x_{C-1}, y_{C-1}) is never needed.
> (chore) Remove last `eq` lookup in comparison instructions

- jolt-core/src/host/mod.rs
This dramatically reduces the produced RISC-V binary size (for small programs about 4x). 
E.g. the fibonacci guest binary goes from 27KB down to 6KB.
> Strip RISC-V binary

- jolt-core/Cargo.toml
- jolt-core/src/field/mod.rs
- src/build_wasm.rs
Our dependency https://gitlab.com/IrreducibleOSS/binius uses tracing-profile and causes wasm builds to fail. 
Fixed by skipping binius for wasm. Will file another issue for that. 
fixes #472
> fix: WASM build failures because of binius

- jolt-core/src/host/toolchain.rs
- src/main.rs
fix https://github.com/a16z/jolt/issues/464, https://github.com/a16z/jolt/issues/463
> feat: uninstall-toolchain command

- src/main.rs
This import is broken in the file generated by jolt new [project] and the project fails to build as a result. I noticed this while doing the quickstart. Sorry if this was fixed already and has to do with an old version of Jolt on my computer.
> Fix bug in default jolt fibonacci template

- jolt-core/src/benches/bench.rs
- jolt-core/src/host/mod.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/jolt/vm/rv32i_vm.rs
- jolt-sdk/macros/src/lib.rs
- jolt-sdk/src/host_utils.rs
Memory layout is a public input to the Jolt verifier and doesn't need to be trusted from the Proof
fixes https://github.com/a16z/jolt/issues/490
> fix: add memory_layout to preprocessing so verifier doesn't rely on the prover

- jolt-core/src/poly/sparse_interleaved_poly.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/sparse_grand_product.rs
- jolt-core/src/subprotocols/sumcheck.rs
Uses the Dao-Thaler EQ optimization in the first Spartan sumcheck. 
This PR also includes some changes to hopefully fix the weird behavior (seemingly introduced by https://github.com/a16z/jolt/pull/481) where `SparseInterleavedPolynomial::layer_output` and `BatchedGrandProductToggleLayer::layer_output` are sometimes an order of magnitude or more slower than usual
> Use SplitEqPolynomial in Spartan cubic sumcheck

- jolt-core/src/jolt/vm/timestamp_range_check.rs
- jolt-core/src/lasso/memory_checking.rs
this probably slipped through when I was working on https://github.com/a16z/jolt/pull/453
> Optimize memory-checking openings for 0s and 1s

- jolt-core/benches/grand_product.rs
- jolt-core/src/subprotocols/grand_product.rs
- jolt-core/src/subprotocols/grand_product_quarks.rs
- jolt-core/src/subprotocols/mod.rs
- jolt-core/src/subprotocols/sparse_grand_product.rs
fixes https://github.com/a16z/jolt/issues/496
> feat: toggled quark hybrid grand product

- jolt-core/benches/grand_product.rs
- jolt-core/src/poly/dense_interleaved_poly.rs
fixes the benchmark and also a bug in the dense interleaved poly implementation.
> fix Grand Product benches

- jolt-core/src/jolt/instruction/divu.rs
- jolt-core/src/jolt/instruction/remu.rs
We return the correct output from sequence output when the divisor is zero, for divu and remu.
Should fix #499
> fix(jolt-core): Fixes DIVU and REMU sequence_output

- jolt-core/src/jolt/instruction/virtual_assert_valid_signed_remainder.rs
- jolt-core/src/jolt/instruction/virtual_assert_valid_unsigned_remainder.rs
This PR does two things:
1. It fixes the panic behavior in `AssertValidSignedRemainder` when either of the operands is the minimum `i32`/`i64` number. This is because `lookup_entry()` invokes `.abs()` which panics when this minimum value is passed in. The fix is to use the panic-free `unsigned_abs()` version instead.
2. It reduces one lookup in `AssertValidUnsignedRemainder`. This savings is similar to the one in `SLTU`, since the less-than unsigned function computation does not require the result of looking up the last chunk to `EqSubtable`.
> fix(jolt-core): Fixes & lookup saving for `ValidRemainder` instrs

- rust-toolchain.toml
This aligns the toolchain with Binius's [rust-toolchain](https://gitlab.com/IrreducibleOSS/binius/-/blob/main/rust-toolchain.toml?ref_type=heads)
By updating the toolchain, we solve the following error on the starter project:
```
cargo run --release
Compiling ark-bn254 v0.4.0
Compiling binius_field v0.1.0 (https://gitlab.com/UlvetannaOSS/binius#33eab8c9)
error[E0658]: use of unstable library feature 'iter_repeat_n'
--> /Users/user/.cargo/git/checkouts/binius-073c6a8ffd019076/33eab8c/crates/field/src/packed.rs:225:76
|
225 |             self.iter().skip(block_idx * block_len).take(block_len).flat_map(|elem| iter::repeat_n(elem, repeat))
|                                                                                     ^^^^^^^^^^^^^^
|
= note: see issue #104434 …
```
> chore: Update toolchain to nightly-2024-09-30

- Cargo.lock
- jolt-core/Cargo.toml
- jolt-core/src/jolt/vm/rv32i_vm.rs
- jolt-core/src/utils/profiling.rs
- jolt-evm-verifier/script/Cargo.lock
`LazyLock` does the same thing but is built-in as of Rust 1.80.0.
> chore: replace lazy_static with LazyLock

- book/src/usage/install.md
- book/src/usage/quickstart.md
Use the correct nightly version (required by `binius`) when installing `jolt` binary.
Relates to https://github.com/a16z/jolt/issues/508
> fix: make sure the proper nightly version is used

- jolt-evm-verifier/src/subprotocols/SpartanVerifier.sol
This update addresses a minor typo in the comments of the `SpartanVerifier` contract. Specifically, the comment contained the phrase "the the inner sumcheck," which was corrected to "the inner sumcheck."
While this is a small change, maintaining clear and precise comments is crucial for code readability and understanding. Typos, even in comments, can create confusion, especially for other developers reviewing the code or collaborating on future changes. By fixing this, we ensure that the documentation remains professional and accurate.
> Fix Minor Typo in Comment Update SpartanVerifier.sol

- book/src/background/risc-v.md
This pull request fixes a broken link in the `risc-v.md` file. The link to the Wagmi documentation was updated to point to the correct URL.
- Fixed `https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md` to `https://github.com/riscv-non-isa/riscv-asm-manual/blob/main/src/asm-manual.adoc`.
> fix: broken link risc-v.md

- book/src/background/binius.md
The phrase "for to be combined" is incorrect. This phrase looks more correct:
"The Binius paper also gives a number of sum-check-based polynomial IOPs to be combined with the commitment scheme."
This adjustment removes the unnecessary "for," making the sentence grammatically correct.
> doc: fix grammar Update binius.md

- book/src/how/sparse-constraint-systems.md
This pull request corrects two instances of improper hyphenation in the file `sparse-constraint-systems.md`. The term **"left hand side"** has been updated to **"left-hand side"** to follow standard grammatical rules for compound adjectives.  
- Updated "left hand side" to "left-hand side" in two locations:  
1. Line 27: Explanation of constraint modification.  
2. Line 68: Discussion of sparsity in constraint systems.
>  Fix hyphenation in "left-hand side" in sparse-constraint-systems.md  

- Cargo.lock
- jolt-core/Cargo.toml
- jolt-core/src/benches/bench.rs
- jolt-core/src/poly/eq_poly.rs
- jolt-core/src/subprotocols/mod.rs
- jolt-core/src/subprotocols/twist.rs
Implements the "local" [Twist](https://eprint.iacr.org/2025/105.pdf) offline memory-checking argument, for the special case of $d = 1$. The fast prover implementation of this algorithm is detailed in Section 8.
Note that this implementation is currently standalone –– it is not hooked up to a polynomial commitment scheme or to the rest of Jolt.
> Twist, d=1

- README.md
- jolt-core/src/jolt/instruction/add.rs
- jolt-core/src/jolt/instruction/mul.rs
- jolt-core/src/jolt/instruction/mulu.rs
- jolt-core/src/jolt/instruction/sub.rs
- jolt-core/src/jolt/instruction/virtual_advice.rs
- jolt-core/src/jolt/subtable/mod.rs
- jolt-core/src/jolt/vm/rv32i_vm.rs
The truncateOverflow subtable always returns 0 with WORD_SIZE = 32 or 64 bits. All the calls to this subtable are eliminated.
> Remove unnecessary truncateOverflow subtable

- jolt-core/benches/commit.rs
I noticed that the `mode` parameter wasn’t being passed to the function, causing issues. To resolve this, I removed the reference to `mode`, which was unnecessary. Now the function works correctly and compiles without errors.
Here’s the updated line:
```rust
&format!("{} Commit(threshold: {}% Ones)", name, threshold),
```
> chore: fix issue with missing mode parameter in the function

- .github/workflows/rust.yml
- book/src/future/groth-16.md
- book/src/future/proof-size-breakdown.md
- book/src/how/m-extension.md
- book/src/how/r1cs_constraints.md
- book/src/how/read_write_memory.md
- book/src/how/sparse-constraint-systems.md
- examples/overflow/src/main.rs
- jolt-core/src/lasso/memory_checking.rs
- jolt-core/src/poly/commitment/hyrax.rs
- jolt-core/src/poly/commitment/zeromorph.rs
- jolt-core/src/poly/sparse_interleaved_poly.rs
- jolt-core/src/poly/spartan_interleaved_poly.rs
- jolt-core/src/r1cs/inputs.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/sparse_grand_product.rs
- jolt-core/src/subprotocols/sumcheck.rs
- jolt-core/src/subprotocols/twist.rs
- jolt-core/src/utils/thread.rs
- tracer/src/emulator/cpu.rs
- tracer/src/emulator/device/virtio_block_disk.rs
- tracer/src/emulator/mmu.rs
- tracer/src/emulator/mod.rs
- typos.toml
I noticed a typo in the book ('lik' instead of 'like') and decided to fix it, and also check for other typos along the way with [typos](https://crates.io/crates/typos).
This PR:
- fixes all detected typos in code and docs
- adds a CI job for typos detection
> chore: fix typos in code & docs, add CI job

- jolt-core/src/poly/eq_poly.rs
- jolt-core/src/poly/multilinear_polynomial.rs
- jolt-core/src/r1cs/constraints.rs
- jolt-core/src/r1cs/key.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/sumcheck.rs
Optimization crushing the second Spartan sumcheck. Instead of the inner sumcheck with `a * b` rounds where `a = num_vars_padded` and `b = num_steps_padded`, we now perform two sumchecks of `a` rounds and `b` rounds, respectively. 
There's a lot to document. I'm making the PR for now to unblock @moodlezoup's other optimizations. 
Edit: The below change is no longer needed. The optimization works with the trace as is. 
~~A *major* change in the code that we should discuss before merging:~~ 
- ~~There was an issue with how the cross-step (also called "non-uniform" constraints) were handled for the last step. Now, the changes in this PR assume that all witness elements belonging to the last step are 0, so the step is effectively ignored. This requires some changes to the trace polynomials (in …
> The Return of the King

- tracer/src/emulator/memory.rs
I've corrected the bit shift error in the `read_doubleword` function. The shift in the original implementation was incorrectly set to 4 bits:
```rust
(self.read_word(address.wrapping_add(4)) as u64) << 4
```
It has now been updated to 32 bits to ensure the correct behavior:
```rust
(self.read_word(address.wrapping_add(4)) as u64) << 32
```
This should resolve the issue and properly align the data.
> fix: Fix incorrect bit shift in read_doubleword function

- examples/fibonacci/src/main.rs
I copied the input from the `analyze_fib` function instead of from `prove_fib`, so [the action that runs the examples failed](https://github.com/a16z/jolt/actions/runs/14324219897/job/40146699700). This should fix it!
> fix prover input in fibonacci

- Cargo.lock
- jolt-core/src/field/ark.rs
- jolt-core/src/field/mod.rs
- jolt-core/src/poly/commitment/kzg.rs
- jolt-core/src/poly/spartan_interleaved_poly.rs
- jolt-evm-verifier/script/Cargo.lock
WIP
This PR is downstream of new progress in [v0.5.0-optimize-mul-u64](https://github.com/a16z/arkworks-algebra/tree/v0.5.0-optimize-mul-u64), where we defined `mul_u128` and `mul_i128` using Barrett reduction, similar to `mul_u64`.
The new arkworks version also restores the `FixedBase` trait that is needed for `kzg.rs`. Without it, we got a bench timeout.
Finally, we also change the `from_u64` function for BN254 to call `from_u64` in arkworks instead (if the number fits in u16 or u32 then we call that). The reason is that doing 4 lookups + adding them together is slightly slower than just doing a single `Fr::one().mul_u64(val)`. But of course <=2 lookups is faster.
> feat: add optimized `mul_i128`, change `from_u64`, revert `FixedBase` change

- build.rs
- src/main.rs
This PR introduces a new `build.rs` file that retrieves the latest Git commit hash, short hash, and date, and sets them as environment variables for use in the application. Additionally, the `main.rs` file is updated to include a version function that formats the version string with the Git information.
> chore: add build script to capture Git commit information

- examples/run_benchmarks.sh
- jolt-sdk/macros/src/lib.rs
Also fixes `./examples/run_benchmarks.sh` to work on MacOS as long as gtime is installed.
> fix: guest programs using stdlib

- Cargo.lock
- jolt-core/Cargo.toml
- jolt-core/src/jolt/vm/rv32i_vm.rs
The error "cannot find value `inner` in this scope" occurs because enum_dispatch
creates an inner identifier during macro expansion, but it's not properly scoped.
The paste crate helps by creating hygienic identifiers during macro expansion,
ensuring the inner value is available in the correct scope.
This is a more robust solution than relying on trait definition order, as it
properly handles macro hygiene and identifier scoping.
> fix: use paste crate to resolve enum_dispatch inner scope issue

- jolt-core/src/field/mod.rs
- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/instruction_lookups.rs
- jolt-core/src/jolt/vm/read_write_memory.rs
- jolt-core/src/jolt/vm/timestamp_range_check.rs
- jolt-core/src/lasso/memory_checking.rs
- jolt-core/src/lasso/surge.rs
- jolt-core/src/lib.rs
This commit removes the associated_type_defaults feature flag and makes all associated types explicit in the codebase. The changes include:
- Remove #![feature(associated_type_defaults)] from lib.rs
- Remove default value (= ()) from JoltField::SmallValueLookupTables
- Remove default values from MemoryCheckingProver associated types:
- ReadWriteGrandProduct
- InitFinalGrandProduct
- ExogenousOpenings
- Preprocessing
- MemoryTuple
- Make all implementations of MemoryCheckingProver explicitly specify their associated types
- Reorder associated type declarations for better readability
These changes make the code more explicit and remove the dependency on the unstable associated_type_defaults feature, improving compatibility with stable Rust.
> refactor: remove associated_type_defaults feature flag

- common/Cargo.toml
- common/src/attributes.rs
- common/src/lib.rs
- common/src/rv_trace.rs
This is Step 1 in a long line of steps towards making `jolt` `no_std` compliant.
> Make the `common` crate `no_std`-compliant

- jolt-core/src/poly/eq_poly.rs
- jolt-core/src/poly/unipoly.rs
- jolt-core/src/subprotocols/shout.rs
- jolt-core/src/subprotocols/sumcheck.rs
Adds an abstraction for running multiple sumchecks in parallel (aka batching). 
Currently we does this manually in a few places, but it quickly gets messy and verbose. 
That said, there are cases where we can gain some efficiency by a more bespoke batching implementation, e.g. when two sumcheck instances have some polynomials in common. In such a case, we would use a single `BatchableSumcheckInstance` for that pair of sumchecks, and then batch the *batched* sumcheck with other instances.
See, for example, the proof-of-concept usage of the new abtraction in `shout.rs`, where we use bespoke batching for the core PIOP sumcheck and the Hamming weight sumcheck, then use the new `BatchedSumcheck` to batch that with the booleanity sumcheck.
> [JOLT-117] Feat/batched sumcheck

- jolt-core/src/msm/icicle/mod.rs
- jolt-core/src/poly/commitment/bmmtv/hyperbmmtv.rs
- jolt-core/src/poly/commitment/bmmtv/poly_commit.rs
- jolt-core/src/poly/eq_poly.rs
- jolt-core/src/poly/spartan_interleaved_poly.rs
- jolt-core/src/poly/split_eq_poly.rs
- jolt-core/src/poly/unipoly.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/sumcheck.rs
This PR implements multiple optimizations for Spartan's first sum-check:
1. We implement Gruen's optimization 
2. We also implement the optimization that in the first sum-check round, there is no need to compute the evaluation at zero, since it is zero due to R1CS relation being satisfied
3. Finally, we change the output type of `unbound_coeffs` to be a vector of chunks of sparse coefficients, instead of a unified vector of coefficients. This eliminates the coalescing at the end of `new()`, and chunking at the beginning of `first_sumcheck_round()`. Instead, we now just pass these parallel chunks from one function directly to the other. In theory, I could also keep the chunks separate for the next few rounds of `subsequent_sumcheck_round()`, but not sure if it's worth it. When we switch to …
> feat: implement gruen's optimization & more for spartan

- Cargo.lock
- jolt-core/src/host/mod.rs
- tracer/Cargo.toml
- tracer/src/emulator/cpu.rs
- tracer/src/emulator/default_terminal.rs
- tracer/src/emulator/device/uart.rs
- tracer/src/emulator/device/virtio_block_disk.rs
- tracer/src/emulator/elf_analyzer.rs
- tracer/src/emulator/memory.rs
- tracer/src/emulator/mmu.rs
- tracer/src/emulator/mod.rs
- tracer/src/lib.rs
- tracer/src/trace.rs
This requires a slight change to the API that is exposed to `jolt-core`: The `trace` function no longer takes a `PathBuf` (since that's not available in a `no_std` environment) and instead takes the elf contents as a `Vec<u8>`. This requires a slight change to the `jolt-core` `host` module to make that API change compatible.
> Make `tracer` `no_std` compatible

- README.md
- book/src/future/improvements-since-release.md
- book/src/opts.md
- book/src/people.md
- jolt-core/src/benches/bench.rs
- jolt-core/src/field/mod.rs
- jolt-core/src/poly/dense_interleaved_poly.rs
- jolt-core/src/poly/sparse_interleaved_poly.rs
- jolt-core/src/poly/spartan_interleaved_poly.rs
- jolt-core/src/poly/split_eq_poly.rs
- jolt-core/src/r1cs/builder.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/sumcheck.rs
- jolt-core/src/utils/mod.rs
- jolt-core/src/utils/small_value.rs
This PR overhauls the Spartan first sum-check to use small-value optimization (SVO). This will be described in detail in an upcoming paper by Bagad-Dao-Domb-Thaler, itself a merge of two prior works [BDT24] and [DT24].
We currently settle on 3 rounds of SVO as that leads to the most performance improvement (both estimated and demonstrated in benchmarks). When we do streaming, we may want to do 4 rounds of SVO instead, as the extra SVO round is slightly less expensive than one streaming round.
Some miscellaneous changes include:
- Update parts of the book to reflect the changes
- Update `bench.rs` which currently gives an error (`decode()` needs to be _after_ `trace()`, not before)
- Update README to have the correct command for profiling (`profile` instead of `trace`)
There was a prior …
> feat: small value optimization for Spartan

- zklean-extractor/src/constants.rs
- zklean-extractor/src/r1cs.rs
A recent PR made the ZkLean extractor fail to compile. This fixes it.
> Update extractor to use new memory config struct

- LICENSE-APACHE
- LICENSE-MIT
This PR updates Jolt's license from MIT to MIT + Apache 2.0 ("dual license").
> updates license from MIT to MIT + Apache 2.0

- common/src/attributes.rs
- common/src/constants.rs
- common/src/rv_trace.rs
- jolt-core/src/jolt/instruction/sh.rs
- jolt-core/src/jolt/vm/mod.rs
- jolt-core/src/poly/commitment/bmmtv/hyperbmmtv.rs
- jolt-core/src/poly/commitment/commitment_scheme.rs
- jolt-core/src/poly/commitment/hyperkzg.rs
- jolt-core/src/poly/commitment/kzg.rs
- jolt-core/src/poly/commitment/mock.rs
- jolt-core/src/poly/commitment/zeromorph.rs
- jolt-sdk/macros/src/lib.rs
- Fixed a bug where virtual sequences generated for SH were failing alignment checks.
- Add max_trace_length and max_bytecode_size to `provable` attribtues
- Improved error reporting
> fix: SH virtual instruction alignment check

- jolt-core/src/poly/identity_poly.rs
For some reason these asserts were causing multiplication overflow when running tests locally, even though CI passed? idk
> Remove debug asserts

- Cargo.lock
- tracer/Cargo.toml
- tracer/src/emulator/cpu.rs
- tracer/src/emulator/elf_analyzer.rs
- tracer/src/emulator/mmu.rs
- tracer/src/emulator/mod.rs
- tracer/src/instruction/addiw.rs
- tracer/src/instruction/addw.rs
- tracer/src/instruction/divuw.rs
- tracer/src/instruction/divw.rs
- tracer/src/instruction/format/format_u.rs
- tracer/src/instruction/jalr.rs
- tracer/src/instruction/ld.rs
- tracer/src/instruction/lui.rs
- tracer/src/instruction/lwu.rs
- tracer/src/instruction/mod.rs
- tracer/src/instruction/mulw.rs
- tracer/src/instruction/remuw.rs
- tracer/src/instruction/remw.rs
- tracer/src/instruction/sd.rs
- tracer/src/instruction/slliw.rs
- tracer/src/instruction/sllw.rs
- tracer/src/instruction/sraiw.rs
- tracer/src/instruction/sraw.rs
- tracer/src/instruction/srliw.rs
- tracer/src/instruction/srlw.rs
- tracer/src/instruction/subw.rs
- tracer/src/main.rs
This PR adds comprehensive RV64IM instruction support to the Jolt tracer. It passes riscv-arch-tests.
- **Load/Store**: `LD`, `LDU`, `SD` for 64-bit memory operations
- **Arithmetic**: `ADDIW`, `SLLIW`, `SRLIW`, `SRAIW` for 32-bit operations with sign extension
- **Control Flow**: Enhanced `JALR` implementation with proper RISC-V compliance
- **Shift Operations**: `SLLW`, `SRLW`, `SRAW` with proper 32-bit operand handling
- **Multiplication**: `MULW`, `DIVW`, `DIVUW` for 32-bit arithmetic
- **Division**: `REMW`, `REMUW` for remainder operations
- **Testing Framework**: Trace mode toggle for debugging and testing
- **Signature Generation**: Support for test result validation
- **Compressed Instructions**: Improved RISC-V C extension compliance
- **Format Parsing**: Fixed immediate value …
> feat: Add RV64IM instruction support

- jolt-core/src/jolt/vm/bytecode.rs
- jolt-core/src/jolt/vm/output_check.rs
- jolt-core/src/jolt/vm/ram.rs
- jolt-core/src/jolt/vm/ram_read_write_checking.rs
- jolt-core/src/jolt/vm/registers.rs
- jolt-core/src/jolt/vm/registers_read_write_checking.rs
- jolt-core/src/poly/opening_proof.rs
- jolt-core/src/r1cs/spartan.rs
- jolt-core/src/subprotocols/ra_virtual.rs
- jolt-core/src/subprotocols/shout.rs
- jolt-core/src/subprotocols/sumcheck.rs
This PR uses `GruenSplitEqPolynomial` to add Dao-Thaler and Gruen's optimizations to some Twist and Shout sumchecks. The sumchecks currently handled are
- The read-write register sumcheck [here](https://github.com/a16z/jolt/blob/feat/twist-shout-integration/jolt-core/src/jolt/vm/registers_read_write_checking.rs#L362)
- The read-write RAM sumcheck [here](https://github.com/a16z/jolt/blob/feat/twist-shout-integration/jolt-core/src/jolt/vm/ram_read_write_checking.rs)
Some caveats:
- The optimization is only applied to phase 1 of the RAM and register sumchecks. Phases 2 and 3 use high-to-low binding, whereas `GruenSplitEqPolynomial` currently assumes low-to-high, so it would need to be modified to switch binding modes in the middle. This also means that some of the precomputed eq values in …
> Add Dao-Thaler and Gruen's optimizations to Twist and Shout sumchecks

- jolt-core/benches/compact_poly_bench.rs
- jolt-core/benches/poly_bench.rs
- jolt-core/src/poly/multilinear_polynomial.rs
Renamed 
MultilinearPoly.evaluate --> MultilinearPoly.evaluate_dot_product
MultiLinearPoly.optimised_evaluate --> MultilinearPoly.evaluate
This is makes sure all functions calling optimised polynomial evaluate get the constant factor speedups without having to change how they invoke polynomial evaluation.
The bench code is also changed to accommodate naming changes
> Renaming polynomial evaluation function names

- common/src/constants.rs
- common/src/jolt_device.rs
- jolt-core/src/benches/bench.rs
- jolt-core/src/host/mod.rs
- jolt-core/src/zkvm/dag/mod.rs
- jolt-core/src/zkvm/mod.rs
- jolt-sdk/macros/src/lib.rs
- src/build_wasm.rs
- tracer/src/emulator/mmu.rs
- tracer/src/emulator/mod.rs
- tracer/src/lib.rs
- aligned linker and emulator memory region sizes
- ensure bytecode size is known before constructing MemoryLayout so that bounds checks can be enforced
- aligned DRAM_BASE and RAM_START_ADDRESS
- made JoltDevice optional in mmu instead of initializing it with a dummy memory layout
> fix: Assumptions about stack and heap locations in MemoryLayout

- jolt-core/src/utils/small_value.rs
When moving to RV64, the values in Spartan first sum-check roughly doubles in bit-size.
This means that the small-value optimization must also change. Before, we could fit `az_eval` and `bz_eval` in i64 (really about 33 bits), and so their product fits in i128. Now each of them is `i128` (really about 65 bits), but their product would overflow i128.
The solution is to replace `E_in.mul_i128( az_eval * bz_eval)` with `E_in.mul_i128(az_eval).mul_i128(bz_eval)`. This doubles the number of field times i128 mults, but recovers correctness. Should be fine since we expect things to slow down by ~2x when we move to RV64 anyway. Also, it slows down just the SVO part, which is not too much.
> feat: modify small value optimization to work with RV64

- jolt-core/src/poly/one_hot_polynomial.rs
- jolt-core/src/zkvm/bytecode/booleanity.rs
- jolt-core/src/zkvm/instruction_lookups/booleanity.rs
- jolt-core/src/zkvm/ram/booleanity.rs
- drops various data structures when they are not needed
- Optimizes batching sumcheck sparse case to use F for the first round of T variables to avoid materializing H to save memory
- Otherwise cuts most of the memory across the board by half and we observe more or less the theoretical 1 GiB / 2^20 cycles (other than spartan which is known, a constant spike in instructions and some overhead still in batching sumcheck)
> Drop sumcheck data structures

- tracer/src/instruction/div.rs
- tracer/src/instruction/mulhsu.rs
- tracer/src/instruction/rem.rs
- tracer/src/instruction/virtual_assert_valid_signed_remainder.rs
- tracer/src/instruction/virtual_movsign.rs
This PR fixes several critical bugs in RISC-V instruction implementations that were causing incorrect behavior in division, remainder, and multiplication operations.
- Remove incorrect remainder adjustment logic that was trying to enforce same sign between remainder and divisor
- Update VirtualAssertValidSignedRemainder to only check magnitude relationship, not sign matching
- Add clarifying comments about RISC-V spec requirements
- Remove the line that overwrites the calculated sign-based value with the original rs1 value
- This was causing VirtualMovsign to return the original input instead of the intended sign indicator (-1 for negative, 0 for non-negative)
- Document the two's complement encoding relationship: MULHSU(rs1, rs2) = MULHU(rs1_unsigned, rs2) - rs2
- Replace MULHU with MUL …
> Fix RISC-V instruction bugs in division, remainder, and multiplication

- examples/btreemap/host/src/main.rs
- jolt-sdk/src/cycle_tracking.rs
- jolt-sdk/src/lib.rs
- jolt-verifier/tests/README.md
- tracer/src/emulator/cpu.rs
- Rust strings are not null terminated. This can cause the cycle tracking print to pickup random bytes as it tries to reconstruct a string from the pointer it has access to.
> fix: cycle tracking marker id length

- examples/verifier/guest/src/lib.rs
- jolt-core/src/zkvm/mod.rs
- This reduces deserialization cost down to 89M from 436M by turning off validation. Still exploring zero copy.
> fix: add option to deserialize Serializable objects without validation

- Makefile
- tracer/src/instruction/amomaxuw.rs
- tracer/src/instruction/amominuw.rs
- tracer/src/instruction/divuw.rs
- tracer/src/instruction/divw.rs
- tracer/src/instruction/remuw.rs
- tracer/src/instruction/remw.rs
- tracer/src/utils/instruction_macros.rs
- Correct instruction definitions of AMOMAXUW, AMOMINUW, DIVUW, DIVW, REMUW, REMW
- Update the instruction macros to include validation checks for matching values.
- Build jolt-emu with debug profile to flush as many as possible issues.
> fix: modify matching values for several RISC-V instructions

- jolt-core/src/msm/mod.rs
1. Replace unsafe (-scalar) as u64 with scalar.unsigned_abs() to safely handle i64::MIN.
2. Move length check before parallel partitioning to avoid unnecessary work on mismatched inputs.
3. Keeps existing MSM structure (pos - neg) while removing UB risk.
> fix(msm): avoid i64::MIN overflow in I64Scalars MSM

- jolt-core/src/zkvm/r1cs/inputs.rs
Previously, we would only parallelize over the (41) R1CS inputs, which led to CPU underutilization on big machines
> More parallelism in compute_claimed_witness_evals

- Cargo.lock
- jolt-core/src/host/program.rs
- jolt-sdk/Cargo.toml
- jolt-sdk/src/getrandom.rs
- jolt-sdk/src/lib.rs
This PR introduces a custom implementation of the `getrandom` backend tailored for RISC-V bare-metal environments, where standard OS-level randomness sources (e.g. `/dev/urandom`, system calls) are unavailable.
- The `getrandom` crate expects platform-specific entropy sources, which do not exist in bare-metal targets.
- Without a custom backend, any crate relying on `getrandom` (e.g. `rand`, `secp256k1`, cryptographic protocols) will fail to compile or panic at runtime.
- RISC-V guest environments require deterministic or syscall-based entropy generation.
- A simple linear congruential generator (LCG) seeded with a fixed value, exposed via a `sys_rand` syscall.
- Implementations for both `getrandom_v02` and `getrandom_v03` interfaces.
- Integration via …
> feat: Add custom getrandom backend for RISC-V bare-metal targets

- Cargo.lock
- jolt-core/src/poly/prefix_suffix.rs
- jolt-core/src/utils/thread.rs
- jolt-core/src/zkvm/instruction_lookups/read_raf_checking.rs
Similar to https://github.com/a16z/jolt/pull/933 but for initializing the suffix polys at the start of each phase, i.e. we now parallelize over chunks of lookup indices. No noticeable performance difference on my Macbook, but should result in better performance on machines with many cores (e.g. Threadripper)
> Parallelize over lookup indices when initializing suffix polys
