src/lib.rs, src/main.rs, src/poly/dense_mlpoly.rs, src/subprotocols/bullet.rs, src/subprotocols/dot_product.rs, src/subprotocols/sumcheck.rs, src/subprotocols/zk.rs, src/subtables/lt.rs, src/utils/errors.rs
Small fixes done while reading the code, including a bit of help in the direction of #20.
=> Drive-by fixes

src/lasso/memory_checking.rs
=> feat(parallelize): parallelize build_grand_product_inputs

src/lasso/memory_checking.rs, src/subprotocols/sumcheck.rs
Closes #31. The parallelization is toggled by the multicore feature.
=> feat(parallelize): parallelize sumcheck::prove_arbitrary summation

src/jolt/instruction/mod.rs, src/jolt/instruction/sll.rs, src/jolt/subtable/mod.rs, src/jolt/subtable/sll.rs, src/jolt/subtable/test.rs, src/jolt/vm/test_vm.rs, src/utils/instruction_utils.rs
Working left shift instruction with one new subtable. The main issue though is that the instruction needs to know the number of chunks. Right now it's hardcoded but we need to change that somehow.
=> Shift Left Instruction

src/jolt/vm/test_vm.rs, src/lasso/fingerprint_strategy.rs
Subtable reuse via summing correct instruction_flags in verifier `FingerprintStrategy`.
Includes separate tests in `test_vm.rs`.
=> Jolt: Subtable Reuse

jolt-core/src/jolt/instruction/sll.rs, jolt-core/src/utils/instruction_utils.rs
Adds `instruction_utils.rs` tests + doc comments.
=> [JOLT-43] instruction_util docs and tests

jolt-core/src/jolt/instruction/add.rs, jolt-core/src/jolt/instruction/jal.rs, jolt-core/src/jolt/instruction/jalr.rs, jolt-core/src/jolt/instruction/mod.rs, jolt-core/src/jolt/instruction/sll.rs, jolt-core/src/jolt/instruction/sra.rs, jolt-core/src/jolt/instruction/srl.rs, jolt-core/src/jolt/instruction/sub.rs, jolt-core/src/jolt/subtable/sll.rs, jolt-core/src/jolt/subtable/sra_sign.rs, jolt-core/src/jolt/subtable/srl.rs, jolt-core/src/jolt/subtable/truncate_overflow.rs, jolt-core/src/jolt/trace/rv.rs, jolt-core/src/jolt/vm/rv32i_vm.rs, jolt-core/src/utils/instruction_utils.rs
=> [JOLT-60] const generic word size

jolt-core/Cargo.toml, jolt-core/benches/dense_mlpoly.rs, jolt-core/benches/sumcheck.rs, jolt-core/src/benches/README.md, jolt-core/src/benches/bench.rs, jolt-core/src/jolt/vm/instruction_lookups.rs, jolt-core/src/lasso/memory_checking.rs, jolt-core/src/lib.rs, jolt-core/src/poly/dense_mlpoly.rs, jolt-core/src/poly/eq_poly.rs, jolt-core/src/subprotocols/sumcheck.rs, jolt-core/src/utils/mod.rs
Init benches
~60% sumcheck speedup with parallelism.
=> Benches + Sumcheck speedup

jolt-core/src/benches/bench.rs, jolt-core/src/jolt/trace/mod.rs, jolt-core/src/jolt/trace/rv.rs, jolt-core/src/jolt/vm/bytecode.rs, jolt-core/src/jolt/vm/instruction_lookups.rs, jolt-core/src/jolt/vm/mod.rs, jolt-core/src/jolt/vm/pc.rs, jolt-core/src/jolt/vm/read_write_memory.rs, jolt-core/src/jolt/vm/rv32i_vm.rs
=> Wiring part 1

common/src/lib.rs, jolt-core/src/jolt/trace/rv.rs, jolt-core/src/jolt/vm/mod.rs, jolt-core/src/jolt/vm/read_write_memory.rs, tracer/src/emulator/cpu.rs, tracer/src/emulator/mod.rs, tracer/src/lib.rs
=> [JOLT-73] Load bytecode to memory on init

jolt-core/src/jolt/instruction/mod.rs, jolt-core/src/jolt/subtable/mod.rs, jolt-core/src/jolt/vm/instruction_lookups.rs, jolt-core/src/lasso/memory_checking.rs, jolt-core/src/poly/dense_mlpoly.rs
10-15% speed up on memory checking
=> Parallelize fingerprinting + GrandProductCircuit creation / evaluation

jolt-core/src/jolt/vm/instruction_lookups.rs
=> parallize flag construction

jolt-core/src/jolt/vm/bytecode.rs
~2x speedup on bytecode proofs, small overall.
=> optimize: bytecode

jolt-core/src/jolt/vm/read_write_memory.rs
=> Remove t_read clone

jolt-core/src/poly/eq_poly.rs
`PARALLEL_THRESHOLD` was experimentally chosen
=> Parallelize EqPolynomial::evals

jolt-core/src/jolt/vm/instruction_lookups.rs
More of a refactor than optimization
=> Combine E and flag poly commitments

jolt-core/src/jolt/vm/instruction_lookups.rs, jolt-core/src/msm/mod.rs, jolt-core/src/poly/hyrax.rs, jolt-core/src/poly/pedersen.rs, jolt-core/src/poly/unipoly.rs
Speeds up MSMs by optimizing for small scalars
=> Optimize small-scalar MSMs

jolt-core/src/poly/dense_mlpoly.rs, jolt-core/src/utils/mod.rs
Some micro-optimizations to avoid bounds checks
=> Use zips instead of indexing into vectors

common/src/field_conversion.rs, jolt-core/Cargo.toml, jolt-core/src/jolt/vm/mod.rs, jolt-core/src/jolt/vm/rv32i_vm.rs, jolt-core/src/poly/pedersen.rs, jolt-core/src/r1cs/snark.rs
Adds onto @nanne007's PR #187 to allow conversion from Arkworks -> Spartan in the generator preprocess function.
=> feat: Ark -> Spartan G1 Conversion

common/src/constants.rs, jolt-core/src/jolt/vm/mod.rs, jolt-core/src/r1cs/snark.rs, jolt-core/src/r1cs/spartan.rs
(spartan.rs changes are mostly from rustfmt)
=> Use NUM_R1CS_POLYS=82 for Hyrax aspect ratio

jolt-core/src/jolt/vm/instruction_lookups.rs, jolt-core/src/lasso/memory_checking.rs, jolt-core/src/poly/dense_mlpoly.rs, jolt-core/src/subprotocols/grand_product.rs, jolt-core/src/subprotocols/sumcheck.rs
Various sumcheck optimizations, shaving 100-200ms off of the sha3 benchmark
=> Sumcheck optimizations

jolt-core/src/r1cs/constraints.rs, jolt-core/src/r1cs/snark.rs
=> optimize: Aux var calculation

jolt-core/src/jolt/vm/bytecode.rs, jolt-core/src/r1cs/constraints.rs, jolt-core/src/r1cs/snark.rs
r1cs verification is still failing
=> Prepend no-op to bytecode instead of appending it

jolt-core/src/jolt/instruction/add.rs, jolt-core/src/jolt/instruction/and.rs, jolt-core/src/jolt/instruction/beq.rs, jolt-core/src/jolt/instruction/bge.rs, jolt-core/src/jolt/instruction/bgeu.rs, jolt-core/src/jolt/instruction/bne.rs, jolt-core/src/jolt/instruction/lb.rs, jolt-core/src/jolt/instruction/lh.rs, jolt-core/src/jolt/instruction/mod.rs, jolt-core/src/jolt/instruction/or.rs, jolt-core/src/jolt/instruction/sb.rs, jolt-core/src/jolt/instruction/sh.rs, jolt-core/src/jolt/instruction/sll.rs, jolt-core/src/jolt/instruction/slt.rs, jolt-core/src/jolt/instruction/sltu.rs, jolt-core/src/jolt/instruction/sra.rs, jolt-core/src/jolt/instruction/srl.rs, jolt-core/src/jolt/instruction/sub.rs, jolt-core/src/jolt/instruction/sw.rs, jolt-core/src/jolt/instruction/xor.rs, jolt-core/src/jolt/vm/mod.rs
=> Change operands and operand_chunks to return tuple instead of array

book/src/usage/troubleshooting.md, common/src/rv_trace.rs, examples/fibonacci/src/main.rs, jolt-core/Cargo.toml, jolt-core/src/host/analyze.rs, jolt-core/src/host/mod.rs, jolt-core/src/jolt/instruction/add.rs, jolt-core/src/jolt/instruction/and.rs, jolt-core/src/jolt/instruction/beq.rs, jolt-core/src/jolt/instruction/bge.rs, jolt-core/src/jolt/instruction/bgeu.rs, jolt-core/src/jolt/instruction/bne.rs, jolt-core/src/jolt/instruction/lb.rs, jolt-core/src/jolt/instruction/lh.rs, jolt-core/src/jolt/instruction/mod.rs, jolt-core/src/jolt/instruction/or.rs, jolt-core/src/jolt/instruction/sb.rs, jolt-core/src/jolt/instruction/sh.rs, jolt-core/src/jolt/instruction/sll.rs, jolt-core/src/jolt/instruction/slt.rs, jolt-core/src/jolt/instruction/sltu.rs, jolt-core/src/jolt/instruction/sra.rs, jolt-core/src/jolt/instruction/srl.rs, jolt-core/src/jolt/instruction/sub.rs, jolt-core/src/jolt/instruction/sw.rs, jolt-core/src/jolt/instruction/xor.rs, jolt-core/src/jolt/vm/bytecode.rs, jolt-core/src/jolt/vm/rv32i_vm.rs, jolt-sdk/macros/src/lib.rs
Should make it easier to debug ppls issues without requiring sharing a full repo.
Additionally down the road will give us better integration tests and binary searching for failing instructions within a program.
=> feat: Save program traces to file

book/src/intro.md
- fix some typos
- replace long running sentence with some bullet points
=> Edit book intro

examples/stdlib/guest/src/lib.rs, examples/stdlib/src/main.rs, jolt-sdk/macros/src/lib.rs, jolt-sdk/src/alloc.rs
Note: must install new jolt toolchain to use stdlib (ci release running now in rust fork).
=> fix: allocator

jolt-core/src/lib.rs
Fixes #334 – at some point we should address general exports, opened #337
=> Make utils public

jolt-core/src/host/toolchain.rs
=> Retry downloading the toolchain

jolt-core/benches/iai.rs, jolt-core/src/benches/bench.rs, jolt-core/src/jolt/vm/rv32i_vm.rs, jolt-core/src/poly/commitment/hyperkzg.rs, jolt-core/src/poly/commitment/mod.rs, jolt-core/src/poly/commitment/zeromorph.rs, jolt-core/src/subprotocols/grand_product.rs, jolt-core/src/utils/transcript.rs
based on this branch https://github.com/a16z/jolt/pull/339
and modifications of https://github.com/microsoft/Nova/blob/main/src/provider/hyperkzg.rs
related to https://github.com/a16z/jolt/issues/208
=> feat: hyperkzg pcs

jolt-core/Cargo.toml, jolt-core/src/r1cs/spartan.rs, jolt-core/src/utils/mod.rs, jolt-core/src/utils/profiling.rs
Adds util functions to print current RAM usage and report memory usage deltas for "memory tracing spans"
=> Memory usage utils

jolt-core/src/field/ark.rs, jolt-core/src/field/binius.rs, jolt-core/src/field/mod.rs, jolt-core/src/poly/commitment/hyperkzg.rs, jolt-core/src/poly/commitment/kzg.rs, jolt-core/src/r1cs/builder.rs, jolt-core/src/r1cs/jolt_constraints.rs, jolt-core/src/r1cs/key.rs, jolt-core/src/r1cs/ops.rs, jolt-core/src/r1cs/spartan.rs, jolt-core/src/subprotocols/grand_product.rs, jolt-core/src/subprotocols/grand_product_quarks.rs
=> Implement JoltField Arithmetic by Reference

jolt-core/src/poly/commitment/hyperkzg.rs, jolt-core/src/utils/transcript.rs, jolt-evm-verifier/script/Cargo.toml, jolt-evm-verifier/script/src/bin/hyperkzg_batch_example.rs, jolt-evm-verifier/script/src/bin/hyperkzg_example.rs, jolt-evm-verifier/script/src/bin/transcript_example.rs, jolt-evm-verifier/script/src/main.rs, jolt-evm-verifier/src/reference/Fr.sol, jolt-evm-verifier/src/subprotocols/FiatShamirTranscript.sol, jolt-evm-verifier/src/subprotocols/HyperKZG.sol, jolt-evm-verifier/test/TestHyperKZG.sol
Adds an onchain hyperkzg verifier subprotocol which can verify either single or batch openings.
=> Adds a hyperkzg subprotocol to the onchcain verifier

tracer/src/emulator/cpu.rs
=> Fix emulator implementations of shift instructions

jolt-core/src/jolt/vm/rv32i_vm.rs
=> refac: Comparmentalize Serialization Logic

jolt-core/src/jolt/vm/mod.rs
This is the patch for #436. The changes are minimal and localized to `jolt/vm/mod.rs`.
The resulting verifier is more expensive due to regenerating the constraints, but it seems necessary for soundness.
It should also be compatible with the on-chain verifier, since currently we assume that R1CS constraints are already specified.
=> Move R1CS constraints out of Jolt proof

book/src/usage/wasm_support.md, jolt-sdk/src/host_utils.rs, src/build_wasm.rs
I think this was missing may be mistaken. also anyone getting 
when trying to build-wasm?
=> Serializable

jolt-core/src/jolt/vm/read_write_memory.rs
Closes #478 
This PR fixes two bugs:
1. The construction of `io_witness_range`  in prover and verifier are incorrect.
2. In the verifier, the `io_witness_range_eval` and `v_io_eval` are evaluated incorrectly. It's due to the first bug that we are not able to catch this bug in the test.
=> Fix `OutputSumcheckProof`

jolt-core/Cargo.toml, jolt-core/src/poly/commitment/mod.rs
Discovered more issues with wasm builds. Tested again and this seems to be it.
=> fix: more fixes for WASM builds

README.md
**Description:**
This update addresses two small improvements in the project documentation to enhance clarity and ensure accuracy:
1. **Rust Installation Instructions**:  
The phrase in the **Installation** section was slightly unclear. The original text stated:  
_"it will automatically install the right toolchain and install additional target on the first `cargo` invocation."_  
I’ve updated it to:  
_"it will automatically install the correct toolchain and any additional targets on the first `cargo` invocation."_  
This change makes the message clearer and helps avoid any potential confusion for users.
2. **Clarification of Alpha Status**:  
In the **Quickstart** section, the note regarding Jolt being in alpha used the word "yet," which could imply the alpha status is a temporary …
=> Minor documentation improvements for clarity and accuracy in README.md

Cargo.lock, jolt-core/Cargo.toml, jolt-core/benches/msm_adapter_batch.rs, jolt-core/src/jolt/instruction/remu.rs, jolt-core/src/poly/commitment/zeromorph.rs, jolt-core/src/subprotocols/grand_product_quarks.rs, tracer/src/emulator/device/virtio_block_disk.rs, tracer/src/emulator/elf_analyzer.rs
=> add another bench to more closely measure icicle

jolt-sdk/macros/src/lib.rs
=> fix: Import Serializable trait in wasm verify

jolt-core/benches/binding.rs, jolt-core/src/poly/compact_polynomial.rs
Partially fixes #647 
Also implement binding bench for compact polynomial
=> Implement binding scratch space for compact polynomial

Cargo.lock, tracer/Cargo.toml, tracer/src/emulator/elf_analyzer.rs, tracer/src/emulator/mmu.rs, tracer/src/emulator/mod.rs, tracer/src/main.rs
This PR makes the emulator executable by Riscof and generates a signature.
=> feat: add RISC-V emulator with ELF file execution and signature generation

common/src/rv_trace.rs, jolt-core/src/poly/spartan_interleaved_poly.rs, jolt-core/src/r1cs/constraints.rs
Fixes https://github.com/a16z/jolt/issues/719
=> Add constraint for LUI

jolt-core/src/dag/jolt_dag.rs, jolt-core/src/dag/mod.rs, jolt-core/src/dag/stage.rs, jolt-core/src/dag/state_manager.rs, jolt-core/src/jolt/instruction/mod.rs, jolt-core/src/lib.rs, jolt-core/src/r1cs/inputs.rs, jolt-core/src/r1cs/spartan.rs
Introduces the initial DAG + state manager pattern and the stage 1 integration (spartan propagation)
=> DAG stage 1

jolt-core/src/dag/jolt_dag.rs, jolt-core/src/jolt/vm/bytecode/hamming_weight.rs, jolt-core/src/jolt/vm/bytecode/mod.rs, jolt-core/src/jolt/vm/bytecode/read_checking.rs, jolt-core/src/jolt/vm/instruction_lookups/booleanity.rs, jolt-core/src/jolt/vm/instruction_lookups/read_raf_checking.rs, jolt-core/src/jolt/vm/ram/booleanity.rs, jolt-core/src/jolt/vm/ram/output_check.rs, jolt-core/src/jolt/vm/ram/raf_evaluation.rs, jolt-core/src/jolt/vm/ram/read_write_checking.rs, jolt-core/src/jolt/vm/ram/val_evaluation.rs, jolt-core/src/jolt/vm/registers.rs, jolt-core/src/jolt/vm/registers_read_write_checking.rs, jolt-core/src/poly/identity_poly.rs, jolt-core/src/poly/multilinear_polynomial.rs, jolt-core/src/poly/one_hot_polynomial.rs, jolt-core/src/poly/opening_proof.rs, jolt-core/src/r1cs/spartan.rs
=> Various minor optimizations

jolt-core/src/benches/bench.rs, jolt-core/src/dag/jolt_dag.rs, jolt-core/src/jolt/vm/mod.rs, jolt-core/src/jolt/vm/ram/booleanity.rs, jolt-core/src/jolt/vm/ram/hamming_booleanity.rs, jolt-core/src/jolt/vm/ram/hamming_weight.rs, jolt-core/src/jolt/vm/ram/mod.rs, jolt-core/src/jolt/vm/ram/output_check.rs, jolt-core/src/jolt/vm/ram/ra_virtual.rs, jolt-core/src/jolt/vm/ram/raf_evaluation.rs, jolt-core/src/jolt/vm/ram/read_write_checking.rs, jolt-core/src/jolt/vm/ram/val_evaluation.rs, jolt-core/src/jolt/witness.rs, jolt-core/src/poly/commitment/dory.rs, jolt-core/src/poly/identity_poly.rs, jolt-core/src/poly/one_hot_polynomial.rs, jolt-core/src/poly/opening_proof.rs, jolt-core/src/poly/program_io_polynomial.rs, tracer/src/instruction/inline_sha256/mod.rs
Flagging changes to DAG: in stage 3 there's now hamming booleanity sumcheck that checks hamming weight for booleanity.
=> [JOLT-135] Feat/ram dummy reads optimization

jolt-core/src/benches/bench.rs, jolt-core/src/jolt/vm/instruction_lookups/booleanity.rs, jolt-core/src/jolt/vm/ram/booleanity.rs, jolt-core/src/jolt/vm/ram/read_write_checking.rs, jolt-core/src/jolt/vm/registers/read_write_checking.rs, jolt-core/src/poly/eq_poly.rs, jolt-core/src/poly/one_hot_polynomial.rs, jolt-core/src/poly/split_eq_poly.rs, jolt-core/src/subprotocols/sumcheck.rs
- Adds the Gruen optimization for Booleanity, and RW sumchecks
- batching sumcheck is still TODO
=> [JOLT-152] Gruen for rw checking, booleanity

src/main.rs
=> [JOLT-150] Fix example project templates

jolt-core/src/poly/opening_proof.rs, jolt-core/src/subprotocols/sumcheck.rs, jolt-core/src/utils/errors.rs, jolt-core/src/zkvm/bytecode/mod.rs
Fixes the verification error in the stdlib example
=> Fix UNIMPL instruction address handling 

tracer/src/emulator/mmu.rs
- Ensured assertions related to effective addresses are only performed when `jolt_device` is available.
=> refactor: Refactor MMU to handle JoltDevice absence gracefully

jolt-core/src/zkvm/lookup_table/shift_right_bitmask.rs
Decreased test running time from 12 seconds to under a second. And verifier minor optimizations.
=> [JOLT-180] optimize/Shift right bitmask evaluate MLE

jolt-core/src/host/program.rs
* Added support for a target-specific CC environment variable to configure the compiler.
=> feat: support for a target-specific CC environment variable

jolt-core/src/host/toolchain.rs
This PR add support for resumable download.
* Added functionality to resume downloads if interrupted.
* Implemented checks for partial downloads and adjusted file handling accordingly.
=> feat: support resumable downloads when installing toolchain

jolt-core/src/host/program.rs
- Introduced a new function `compose_command_line` to format the command line for better readability and error handling.
- Simplified the argument passing to the `cargo` command by using an array.
- Improved error reporting by displaying the full command line when a build fails.
=> refactor: streamline cargo command execution and enhance error reporting

Cargo.lock, Cargo.toml, examples/recover-ecdsa/Cargo.toml, examples/recover-ecdsa/guest/Cargo.toml, examples/recover-ecdsa/guest/src/lib.rs, examples/recover-ecdsa/guest/src/main.rs, examples/recover-ecdsa/src/main.rs, jolt-core/src/host/program.rs
This PR adds an example of recovering the public key from the signature.
Please merge #943 first.
=> chore(example): add recover-ecdsa example with ECDSA recovery functionality

jolt-core/benches/large_d_mul.rs, jolt-core/benches/large_d_sumcheck.rs, jolt-core/src/subprotocols/large_degree_sumcheck.rs, jolt-core/src/zkvm/instruction/test.rs
Just small clippy nits while reading the codebase, feel free to accept it or close :)
=> clippy: small nits

jolt-core/src/poly/one_hot_polynomial.rs, jolt-core/src/poly/opening_proof.rs
Splits `OneHotSumcheckState` into two separate structs: `EqAddressState` and `EqCycleState`.
The latter can be shared between one-hot polynomial openings with the same `r_cycle`, but different `r_address`.
To enable this sharing, we add a `HashMap` to `ProverOpeningAccumulator` mapping each `r_cycle` to its `Arc<RwLock<EqCycleState>>`. 
Also, we can defer the `GruenSplitEqPolynomial::merge` until right before we call `prepare_sumcheck`, and drop the merged EQ polynomials as soon as we're done with `prepare_sumcheck`. 
This results in a ~30% reduction in the peak memory usage of Stages 4/5 and a minor end-to-end speedup
Before:
<details>
```
2025-09-19T19:40:32.880611Z DEBUG e2e benchmark:Jolt::prove: "Stage 1 baseline" current memory usage: 19.12 GB
2025-09-19T19:40:32.881116Z  INFO e2e …
```
=> Shared EQ(r_cycle, j) state for Stage 5

jolt-core/src/zkvm/instruction_lookups/hamming_weight.rs, jolt-core/src/zkvm/instruction_lookups/ra_virtual.rs, jolt-core/src/zkvm/ram/hamming_booleanity.rs, jolt-core/src/zkvm/ram/output_check.rs, jolt-core/src/zkvm/ram/ra_virtual.rs, jolt-core/src/zkvm/ram/read_write_checking.rs, jolt-core/src/zkvm/registers/read_write_checking.rs, jolt-core/src/zkvm/registers/val_evaluation.rs, jolt-core/src/zkvm/spartan/inner.rs, jolt-core/src/zkvm/spartan/pc.rs
Makes it easier to SQL query the total cost of a specific sumcheck
=> chore: standardize sumcheck tracing instrumentation

jolt-core/src/poly/opening_proof.rs, jolt-core/src/subprotocols/sumcheck.rs, jolt-core/src/zkvm/bytecode/booleanity.rs, jolt-core/src/zkvm/bytecode/hamming_weight.rs, jolt-core/src/zkvm/bytecode/mod.rs, jolt-core/src/zkvm/bytecode/read_raf_checking.rs, jolt-core/src/zkvm/dag/jolt_dag.rs, jolt-core/src/zkvm/dag/stage.rs, jolt-core/src/zkvm/instruction_lookups/booleanity.rs, jolt-core/src/zkvm/instruction_lookups/hamming_weight.rs, jolt-core/src/zkvm/instruction_lookups/mod.rs, jolt-core/src/zkvm/instruction_lookups/ra_virtual.rs, jolt-core/src/zkvm/instruction_lookups/read_raf_checking.rs, jolt-core/src/zkvm/ram/booleanity.rs, jolt-core/src/zkvm/ram/hamming_booleanity.rs, jolt-core/src/zkvm/ram/hamming_weight.rs, jolt-core/src/zkvm/ram/mod.rs, jolt-core/src/zkvm/ram/output_check.rs, jolt-core/src/zkvm/ram/ra_virtual.rs, jolt-core/src/zkvm/ram/raf_evaluation.rs, jolt-core/src/zkvm/ram/read_write_checking.rs, jolt-core/src/zkvm/ram/val_evaluation.rs, jolt-core/src/zkvm/registers/mod.rs, jolt-core/src/zkvm/registers/read_write_checking.rs, jolt-core/src/zkvm/registers/val_evaluation.rs, jolt-core/src/zkvm/spartan/inner.rs, jolt-core/src/zkvm/spartan/mod.rs, jolt-core/src/zkvm/spartan/pc.rs
fiat-shamir remains undefeated as source of soundness bugs
=> fix: Add sumcheck input and opening claims to transcript

jolt-core/src/poly/opening_proof.rs, jolt-core/src/zkvm/r1cs/constraints.rs, jolt-core/src/zkvm/r1cs/inputs.rs, jolt-core/src/zkvm/spartan/mod.rs, jolt-core/src/zkvm/spartan/product.rs, jolt-core/src/zkvm/witness.rs
Virtualize `Product` witness polynomial, removing one commitment and one R1CS constraint.
=> [JOLT-218] Feat/product virtualization
